using System;
using System.Collections.Generic;
using System.Linq;
using VNotch.Services;
using Xunit;

namespace VNotch.Tests;

public class YouTubeSubtitleServiceTests
{
    [Fact]
    public void SelectCaptionTrack_NativePriority_PicksManualNativeOverAuto()
    {
        // Video with Japanese spoken audio (a.ja) and Japanese manual lyrics (.ja) + English (.en)
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en", false),
            new("ja", "Japanese", ".ja", "https://url/ja_manual", false),
            new("ja", "Japanese (auto-generated)", "a.ja", "https://url/ja_auto", true),
        };

        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"]);
        Assert.Equal("https://url/ja_manual", selected);
    }

    [Fact]
    public void SelectCaptionTrack_NativePriority_PicksAutoNativeIfNoManual()
    {
        // Video with Korean spoken audio (a.ko) and English manual (.en)
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en", false),
            new("ko", "Korean (auto-generated)", "a.ko", "https://url/ko_auto", true),
        };

        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"]);
        Assert.Equal("https://url/ko_auto", selected);
    }


    [Fact]
    public void SelectCaptionTrack_EnglishPriority_PicksEnglishFirst()
    {
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("ja", "Japanese", ".ja", "https://url/ja_manual", false),
            new("en", "English", ".en", "https://url/en_manual", false),
            new("ja", "Japanese (auto)", "a.ja", "https://url/ja_auto", true),
        };

        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["english", "native", "auto"]);
        Assert.Equal("https://url/en_manual", selected);
    }

    [Fact]
    public void SelectCaptionTrack_VietnameseVideo_PicksVietnameseManual()
    {
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("vi", "Tiếng Việt", ".vi", "https://url/vi_manual", false),
            new("vi", "Tiếng Việt (tự động)", "a.vi", "https://url/vi_auto", true),
        };

        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"]);
        Assert.Equal("https://url/vi_manual", selected);
    }

    [Fact]
    public void SelectCaptionTrack_IgnoreAutoGenerated_ReturnsNullWhenOnlyAutoAvailable()
    {
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English (auto-generated)", "a.en", "https://url/en_auto", true),
            new("vi", "Tiếng Việt (tự động)", "a.vi", "https://url/vi_auto", true),
        };

        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"], ignoreAutoGenerated: true);
        Assert.Null(selected);
    }

    [Fact]
    public void SelectCaptionTrack_IgnoreAutoGenerated_PicksManualTrackEvenIfAutoNativeIsHigherPriority()
    {
        // Korean native auto track vs English manual track.
        // With ignoreAutoGenerated = false, native priority picks Korean auto.
        // With ignoreAutoGenerated = true, native priority ignores Korean auto and picks English manual.
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en_manual", false),
            new("ko", "Korean (auto-generated)", "a.ko", "https://url/ko_auto", true),
        };

        string? selectedWithoutIgnore = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"], ignoreAutoGenerated: false);
        Assert.Equal("https://url/ko_auto", selectedWithoutIgnore);

        string? selectedWithIgnore = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"], ignoreAutoGenerated: true);
        Assert.Equal("https://url/en_manual", selectedWithIgnore);
    }

    [Fact]
    public void ParseJson3_ExtractsAndSortsEventSegments()
    {
        const string json = """
        {
            "events": [
                {
                    "tStartMs": 5000,
                    "segs": [{ "utf8": "Hello " }, { "utf8": "World" }]
                },
                {
                    "tStartMs": 2000,
                    "segs": [{ "utf8": "First Line" }]
                }
            ]
        }
        """;

        var lines = YouTubeSubtitleService.ParseJson3(json);
        Assert.Equal(2, lines.Count);
        Assert.Equal("First Line", lines[0].Text);
        Assert.Equal(TimeSpan.FromMilliseconds(2000), lines[0].Time);
        Assert.Equal("Hello World", lines[1].Text);
        Assert.Equal(TimeSpan.FromMilliseconds(5000), lines[1].Time);
    }

    [Fact]
    public void ParseXml_ExtractsAndSortsPAndTextElements()
    {
        const string xml = """
        <transcript>
            <text start="3.5" dur="1.2">Second subtitle</text>
            <text start="1.0" dur="2.0">First subtitle</text>
        </transcript>
        """;

        var lines = YouTubeSubtitleService.ParseXml(xml);
        Assert.Equal(2, lines.Count);
        Assert.Equal("First subtitle", lines[0].Text);
        Assert.Equal(TimeSpan.FromSeconds(1.0), lines[0].Time);
        Assert.Equal("Second subtitle", lines[1].Text);
        Assert.Equal(TimeSpan.FromSeconds(3.5), lines[1].Time);
    }

    [Fact]
    public void GenerateSearchCandidates_YouTubeTitleWithPipesAndGenericArtist_ExtractsCleanedCandidates()
    {
        string rawYouTubeTitle = "JACK - J97 | XÓA TÊN ANH ĐI | Official Music Video | [Album26]";
        string rawYouTubeArtist = "YouTube";

        var candidates = LyricsService.GenerateSearchCandidates(rawYouTubeTitle, rawYouTubeArtist);

        Assert.NotEmpty(candidates);
        Assert.Contains(candidates, c => c.Track == "XÓA TÊN ANH ĐI" && c.Artist == "JACK - J97");
        Assert.DoesNotContain(candidates, c => c.Artist == "YouTube");
    }

    [Fact]
    public void GetOrderedCandidateTracks_WithNativeLangHint_PrioritizesHintedLanguage()
    {
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en_manual", false),
            new("vi", "Tiếng Việt", ".vi", "https://url/vi_manual", false),
            new("ja", "Japanese", ".ja", "https://url/ja_manual", false),
        };

        var ordered = YouTubeSubtitleService.GetOrderedCandidateTracks(tracks, ["native", "english", "auto"], nativeLangHint: "vi");
        Assert.NotEmpty(ordered);
        Assert.Equal("vi", ordered[0].LanguageCode);
    }

    [Fact]
    public void ParseXml_HandlesHtmlEntitiesAndFormattingTags()
    {
        const string xml = """
        <transcript>
            <text start="1.5" dur="2.0">&lt;font color="#cccccc"&gt;Tom &amp;amp; Jerry &#39;Special&#39;&lt;/font&gt;</text>
        </transcript>
        """;

        var lines = YouTubeSubtitleService.ParseXml(xml);
        Assert.Single(lines);
        Assert.Equal("Tom & Jerry 'Special'", lines[0].Text);
        Assert.Equal(TimeSpan.FromSeconds(1.5), lines[0].Time);
    }

    [Fact]
    public void SelectCaptionTrack_VietnameseAndEnglishManual_NoAuto_WithNativePriority_PicksVietnamese()
    {
        // Video with manual Vietnamese (.vi) and manual English (.en), but no auto-generated track
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en_manual", false),
            new("vi", "Tiếng Việt", ".vi", "https://url/vi_manual", false),
        };

        // 1. When nativeLangHint is "vi"
        string? selectedWithHint = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"], nativeLangHint: "vi");
        Assert.Equal("https://url/vi_manual", selectedWithHint);

        // 2. Even without nativeLangHint (null/empty), native priority should prefer non-English manual over English
        string? selectedWithoutHint = YouTubeSubtitleService.SelectCaptionTrackUrl(tracks, ["native", "english", "auto"]);
        Assert.Equal("https://url/vi_manual", selectedWithoutHint);
    }

    [Fact]
    public void SelectCaptionTrack_VietnameseAutoAndEnglishManual_WhenAutoBlocked_PicksEnglishManual()
    {
        // Video with Vietnamese auto-generated (.a.vi / kind:asr) and English manual (.en)
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en_manual", false),
            new("vi", "Tiếng Việt (tự động)", "a.vi", "https://url/vi_auto", true),
        };

        // When ignoreAutoGenerated = true, the auto-generated track MUST be ignored, picking English manual
        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(
            tracks,
            ["native", "english", "auto"],
            nativeLangHint: "vi",
            ignoreAutoGenerated: true);

        Assert.Equal("https://url/en_manual", selected);
    }

    [Fact]
    public void SelectCaptionTrack_VietnameseAutoAndEnglishManual_WhenAutoAllowed_PicksVietnameseAuto()
    {
        // Video with Vietnamese auto-generated (.a.vi) and English manual (.en)
        var tracks = new List<YouTubeCaptionTrack>
        {
            new("en", "English", ".en", "https://url/en_manual", false),
            new("vi", "Tiếng Việt (tự động)", "a.vi", "https://url/vi_auto", true),
        };

        // When ignoreAutoGenerated = false and priority has "native" first, it should pick the Vietnamese auto track
        string? selected = YouTubeSubtitleService.SelectCaptionTrackUrl(
            tracks,
            ["native", "english", "auto"],
            nativeLangHint: "vi",
            ignoreAutoGenerated: false);

        Assert.Equal("https://url/vi_auto", selected);
    }
}
