using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;

namespace VNotch.Services;

/// <summary>
/// Fetches synced closed-caption (subtitle) tracks for YouTube videos using
/// YoutubeExplode and converts them into the same <see cref="LyricLine"/> shape
/// the Spotify lyrics pipeline consumes, so they can be displayed and synced
/// with the exact same UI as synced lyrics.
/// </summary>
internal sealed class YouTubeSubtitleService : IDisposable
{
    // Preferred caption languages, in priority order. The first available track
    // wins; otherwise we fall back to whatever the video offers.
    private static readonly string[] PreferredLanguages = { "en", "en-US", "en-GB", "vi" };

    // YouTube keywords that reliably indicate a music video.
    // YouTube's own systems inject these into music content.
    private static readonly string[] MusicKeywords =
    {
        "music", "song", "lyrics", "official music video", "mv", "audio",
        "nhạc", "bài hát", "lời bài hát"
    };

    private readonly YoutubeClient _youtube = new();

    private CancellationTokenSource? _cts;
    private string _lastFetchKey = "";

    /// <summary>
    /// Fetches the best available synced subtitle track for the given video.
    /// For music videos (detected via YouTube keywords), auto-generated captions
    /// are skipped — only manually-authored tracks are used.
    /// Returns null when no suitable captions exist, the video id is invalid,
    /// the request is cancelled, or the same video was already fetched.
    /// </summary>
    public async Task<List<LyricLine>?> FetchSubtitlesAsync(string videoId)
    {
        if (string.IsNullOrWhiteSpace(videoId)) return null;

        if (videoId == _lastFetchKey) return null; // Already fetched for this video

        // Cancel any in-flight request
        _cts?.Cancel();
        _cts?.Dispose();
        _cts = new CancellationTokenSource();
        var token = _cts.Token;

        // Only commit the fetch key AFTER we have a valid token — if we set it
        // before and then get cancelled, the next call with the same videoId
        // would short-circuit and never retry.
        _lastFetchKey = videoId;

        try
        {
            RuntimeLog.Log("YT-SUBS", $"Fetching captions for videoId={videoId}");

            // Fetch video metadata and caption manifest in parallel — both are
            // needed and neither depends on the other.
            var videoTask = _youtube.Videos.GetAsync(videoId, token);
            var manifestTask = _youtube.Videos.ClosedCaptions.GetManifestAsync(videoId, token);

            await Task.WhenAll(videoTask.AsTask(), manifestTask.AsTask());

            var video = await videoTask;
            var manifest = await manifestTask;

            bool isMusicVideo = IsMusicVideoByKeywords(video.Keywords);
            RuntimeLog.Log("YT-SUBS",
                $"videoId={videoId} isMusicVideo={isMusicVideo} " +
                $"keywords=[{string.Join(", ", video.Keywords.Take(8))}]");

            if (manifest.Tracks.Count == 0)
            {
                RuntimeLog.Log("YT-SUBS", $"No caption tracks for {videoId}");
                return null;
            }

            RuntimeLog.Log("YT-SUBS",
                $"Available tracks: [{string.Join(", ", manifest.Tracks.Select(t => $"{t.Language.Code}(auto={t.IsAutoGenerated})"))}]");

            var trackInfo = SelectTrack(manifest, isMusicVideo);
            if (trackInfo == null)
            {
                RuntimeLog.Log("YT-SUBS",
                    isMusicVideo
                        ? $"No manual caption track for music video {videoId} — skipping auto-generated"
                        : $"No usable caption track for {videoId}");
                return null;
            }

            var track = await _youtube.Videos.ClosedCaptions.GetAsync(trackInfo, token);

            var lines = new List<LyricLine>(track.Captions.Count);
            foreach (var caption in track.Captions)
            {
                string text = caption.Text?.Trim() ?? "";
                if (text.Length == 0) continue;
                lines.Add(new LyricLine(caption.Offset, text));
            }

            lines.Sort((a, b) => a.Time.CompareTo(b.Time));

            RuntimeLog.Log("YT-SUBS",
                $"Got {lines.Count} caption lines for {videoId} " +
                $"(lang={trackInfo.Language.Code}, auto={trackInfo.IsAutoGenerated})");

            return lines.Count > 0 ? lines : null;
        }
        catch (OperationCanceledException)
        {
            // Reset the key so the next call with the same videoId will retry
            // instead of short-circuiting on the stale key.
            if (_lastFetchKey == videoId)
                _lastFetchKey = "";
            return null;
        }
        catch (Exception ex)
        {
            RuntimeLog.Log("YT-SUBS", $"Error fetching {videoId}: {ex.Message}");
            // Also reset on error so a transient failure doesn't permanently
            // block subtitles for this video.
            if (_lastFetchKey == videoId)
                _lastFetchKey = "";
            return null;
        }
    }

    /// <summary>
    /// Determines whether a video is music content by checking its YouTube keywords.
    /// YouTube's own systems inject "music" and related keywords into music videos.
    /// This is more reliable than checking the channel name or artist field.
    /// </summary>
    private static bool IsMusicVideoByKeywords(IReadOnlyList<string> keywords)
    {
        if (keywords == null || keywords.Count == 0) return false;

        foreach (var kw in keywords)
        {
            if (string.IsNullOrWhiteSpace(kw)) continue;
            string lower = kw.ToLowerInvariant();
            foreach (var music in MusicKeywords)
            {
                if (lower == music || lower.Contains(music, StringComparison.Ordinal))
                    return true;
            }
        }
        return false;
    }

    private static ClosedCaptionTrackInfo? SelectTrack(ClosedCaptionManifest manifest, bool isMusicVideo)
    {
        // For music videos: only consider manually-authored tracks.
        // Auto-generated captions on music videos are speech-to-text transcriptions
        // of the audio — they produce garbled lyric fragments, not real subtitles.
        if (isMusicVideo)
        {
            foreach (var lang in PreferredLanguages)
            {
                var manual = manifest.Tracks.FirstOrDefault(
                    t => !t.IsAutoGenerated && LanguageMatches(t, lang));
                if (manual != null) return manual;
            }
            // No preferred-language manual track — accept any manual track.
            return manifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated);
        }

        // For non-music videos: prefer manual tracks in a preferred language,
        // then any manual track, then auto-generated in a preferred language,
        // then any auto-generated track (last resort).
        foreach (var lang in PreferredLanguages)
        {
            var manual = manifest.Tracks.FirstOrDefault(
                t => !t.IsAutoGenerated && LanguageMatches(t, lang));
            if (manual != null) return manual;
        }

        var anyManual = manifest.Tracks.FirstOrDefault(t => !t.IsAutoGenerated);
        if (anyManual != null) return anyManual;

        foreach (var lang in PreferredLanguages)
        {
            var auto = manifest.Tracks.FirstOrDefault(t => LanguageMatches(t, lang));
            if (auto != null) return auto;
        }

        // Last resort: any track at all (covers languages not in PreferredLanguages)
        return manifest.Tracks.FirstOrDefault();
    }

    private static bool LanguageMatches(ClosedCaptionTrackInfo track, string lang)
    {
        string code = track.Language.Code ?? "";
        return code.Equals(lang, StringComparison.OrdinalIgnoreCase)
            || code.StartsWith(lang + "-", StringComparison.OrdinalIgnoreCase)
            || (lang.Contains('-') && lang.StartsWith(code + "-", StringComparison.OrdinalIgnoreCase));
    }

    public void Reset()
    {
        _lastFetchKey = "";
        _cts?.Cancel();
    }

    public void Dispose()
    {
        _cts?.Cancel();
        _cts?.Dispose();
    }
}
