using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;

namespace VNotch.Services;

internal sealed class YouTubeSubtitleService : IDisposable
{

    private string[] _subtitlePriority = { "native", "english", "auto" };

    private static readonly string[] StrongMusicKeywords =
    {
        "official music video", "official video", "official audio",
        "music video", "lyric video", "lyrics video", "visualizer",
        "mv chính thức", "official mv"
    };

    private static readonly string[] MusicDescriptionPatterns =
    {
        "provided to youtube by",
        "auto-generated by youtube",
        "℗",
        "music in this video",
        "nhạc trong video này",
        "licensed to youtube by",
        "official music video",
        "official audio"
    };

    private readonly YoutubeClient _youtube = new();

    private CancellationTokenSource? _cts;
    private string _lastFetchKey = "";
    private int _fetchGeneration;

    public void SetMode(string priorityString)
    {
        if (string.IsNullOrWhiteSpace(priorityString))
        {
            _subtitlePriority = new[] { "native", "english", "auto" };
            return;
        }
        _subtitlePriority = priorityString.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (_subtitlePriority.Length == 0)
            _subtitlePriority = new[] { "native", "english", "auto" };
    }

    public async Task<List<LyricLine>?> FetchSubtitlesAsync(string videoId, bool force = false)
    {
        if (string.IsNullOrWhiteSpace(videoId)) return null;

        if (!force && videoId == _lastFetchKey) return null;

        _cts?.Cancel();
        _cts?.Dispose();
        _cts = new CancellationTokenSource();
        var token = _cts.Token;

        int myGeneration = ++_fetchGeneration;

        _lastFetchKey = videoId;

        try
        {
            RuntimeLog.Log("YT-SUBS", $"Fetching captions for videoId={videoId}");

            var videoTask = _youtube.Videos.GetAsync(videoId, token);
            var manifestTask = _youtube.Videos.ClosedCaptions.GetManifestAsync(videoId, token);

            await Task.WhenAll(videoTask.AsTask(), manifestTask.AsTask());

            var video = await videoTask;
            var manifest = await manifestTask;

            bool isMusicVideo = DetectMusicVideo(video);
            RuntimeLog.Log("YT-SUBS",
                $"videoId={videoId} isMusicVideo={isMusicVideo} " +
                $"duration={video.Duration?.TotalSeconds:F0}s " +
                $"keywords=[{string.Join(", ", video.Keywords.Take(8))}]");

            if (manifest.Tracks.Count == 0)
            {
                RuntimeLog.Log("YT-SUBS", $"No caption tracks for {videoId}");
                return null;
            }

            RuntimeLog.Log("YT-SUBS",
                $"Available tracks: [{string.Join(", ", manifest.Tracks.Select(t => $"{t.Language.Code}(auto={t.IsAutoGenerated})"))}]");

            var trackInfo = SelectTrack(manifest, isMusicVideo);
            if (trackInfo == null)
            {
                RuntimeLog.Log("YT-SUBS",
                    isMusicVideo
                        ? $"No manual caption track for music video {videoId} — skipping auto-generated"
                        : $"No usable caption track for {videoId}");
                return null;
            }

            var track = await _youtube.Videos.ClosedCaptions.GetAsync(trackInfo, token);

            var lines = new List<LyricLine>(track.Captions.Count);
            foreach (var caption in track.Captions)
            {
                string text = caption.Text?.Trim() ?? "";
                if (text.Length == 0) continue;
                lines.Add(new LyricLine(caption.Offset, text));
            }

            lines.Sort((a, b) => a.Time.CompareTo(b.Time));

            RuntimeLog.Log("YT-SUBS",
                $"Got {lines.Count} caption lines for {videoId} " +
                $"(lang={trackInfo.Language.Code}, auto={trackInfo.IsAutoGenerated})");

            return lines.Count > 0 ? lines : null;
        }
        catch (OperationCanceledException)
        {
            if (_fetchGeneration == myGeneration && _lastFetchKey == videoId)
                _lastFetchKey = "";
            return null;
        }
        catch (Exception ex)
        {
            RuntimeLog.Log("YT-SUBS", $"Error fetching {videoId}: {ex.Message}");
            if (_fetchGeneration == myGeneration && _lastFetchKey == videoId)
                _lastFetchKey = "";
            return null;
        }
    }

    private static bool DetectMusicVideo(YoutubeExplode.Videos.Video video)
    {
        string desc = (video.Description ?? "").ToLowerInvariant();
        if (!string.IsNullOrEmpty(desc))
        {
            foreach (var pattern in MusicDescriptionPatterns)
            {
                if (desc.Contains(pattern, StringComparison.Ordinal))
                    return true;
            }
        }

        if (video.Keywords != null && video.Keywords.Count > 0)
        {
            foreach (var kw in video.Keywords)
            {
                if (string.IsNullOrWhiteSpace(kw)) continue;
                string lower = kw.ToLowerInvariant();
                foreach (var strong in StrongMusicKeywords)
                {
                    if (lower == strong || lower.Contains(strong, StringComparison.Ordinal))
                        return true;
                }
            }
        }

        string title = (video.Title ?? "").ToLowerInvariant();
        if (title.Contains("official music video") ||
            title.Contains("official audio") ||
            title.Contains("lyric video") ||
            title.Contains("(official video)") ||
            title.Contains("[official video]") ||
            title.Contains("mv official") ||
            title.Contains("mv chính thức"))
        {
            return true;
        }

        return false;
    }

    private ClosedCaptionTrackInfo? SelectTrack(ClosedCaptionManifest manifest, bool isMusicVideo)
    {
        var tracks = manifest.Tracks;

        foreach (var mode in _subtitlePriority)
        {
            var result = mode switch
            {
                "native" => SelectNative(tracks, isMusicVideo),
                "english" => SelectEnglish(tracks, isMusicVideo),
                "auto" => SelectAuto(tracks, isMusicVideo),
                _ => null
            };
            if (result != null) return result;
        }

        return tracks.FirstOrDefault();
    }

    private static ClosedCaptionTrackInfo? SelectNative(IReadOnlyList<ClosedCaptionTrackInfo> tracks, bool isMusicVideo)
    {

        var autoTrack = tracks.FirstOrDefault(t => t.IsAutoGenerated);
        string? nativeLang = autoTrack?.Language.Code;

        if (!string.IsNullOrEmpty(nativeLang))
        {
            var manualNative = tracks.FirstOrDefault(t =>
                !t.IsAutoGenerated && LanguageCodeMatches(t.Language.Code, nativeLang!));
            if (manualNative != null) return manualNative;

            return autoTrack;
        }

        var nonEn = tracks.FirstOrDefault(t => !t.IsAutoGenerated && !LanguageMatchesEnglish(t));
        if (nonEn != null) return nonEn;

        return tracks.FirstOrDefault(t => !t.IsAutoGenerated);
    }

    private static bool LanguageCodeMatches(string code1, string code2)
    {
        if (string.Equals(code1, code2, StringComparison.OrdinalIgnoreCase)) return true;
        string base1 = code1.Contains('-') ? code1.Split('-')[0] : code1;
        string base2 = code2.Contains('-') ? code2.Split('-')[0] : code2;
        return string.Equals(base1, base2, StringComparison.OrdinalIgnoreCase);
    }

    private static ClosedCaptionTrackInfo? SelectEnglish(IReadOnlyList<ClosedCaptionTrackInfo> tracks, bool isMusicVideo)
    {
        var manual = tracks.FirstOrDefault(t => !t.IsAutoGenerated && LanguageMatchesEnglish(t));
        if (manual != null) return manual;

        var autoEn = tracks.FirstOrDefault(t => t.IsAutoGenerated && LanguageMatchesEnglish(t));
        if (autoEn != null) return autoEn;

        return null;
    }

    private static ClosedCaptionTrackInfo? SelectAuto(IReadOnlyList<ClosedCaptionTrackInfo> tracks, bool isMusicVideo)
    {
        var manual = tracks.FirstOrDefault(t => !t.IsAutoGenerated);
        if (manual != null) return manual;

        return tracks.FirstOrDefault();
    }

    private static bool LanguageMatchesEnglish(ClosedCaptionTrackInfo track)
    {
        var code = track.Language.Code;
        return code == "en" || code.StartsWith("en-", StringComparison.OrdinalIgnoreCase);
    }

    public void Reset()
    {
        _lastFetchKey = "";
        _fetchGeneration++;
        _cts?.Cancel();
    }

    public void Dispose()
    {
        _cts?.Cancel();
        _cts?.Dispose();
    }
}
